name: mailgun_mailer
description: flutter mailgun_mailer
version: 1.0.0
homepage: https://github.com/Mizael55/mailgun_mailer

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  async: ^2.5.0
  http: ^0.13.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
